#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/build/backup-dr-evidence}"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
REPORT="$OUTPUT_DIR/backup-dr-evidence-$TIMESTAMP.md"

mkdir -p "$OUTPUT_DIR"

overall_status=0

run_check() {
  local title="$1"
  shift
  {
    printf '\n# %s\n\n' "$title"
    printf 'GeneratedAt=%s\n\n' "$TIMESTAMP"
    "$@"
  } >>"$REPORT" 2>&1 || overall_status=1
}

{
  printf '# Backup/DR Evidence Report\n\n'
  printf 'GeneratedAt=%s\n\n' "$TIMESTAMP"
  printf 'This report is generated by read-only AWS CLI checks. It may contain AWS resource identifiers; review before sharing externally.\n'
} >"$REPORT"

if [[ -n "${DB_INSTANCE_ID:-}" ]]; then
  run_check "RDS Backup Controls" "$SCRIPT_DIR/check_rds_backup_controls.sh"
else
  {
    printf '\n# RDS Backup Controls\n\n'
    printf 'SKIPPED: DB_INSTANCE_ID is not set.\n'
  } >>"$REPORT"
fi

if [[ -n "${S3_BUCKET:-}" ]]; then
  run_check "S3 Backup Controls" "$SCRIPT_DIR/check_s3_backup_controls.sh"
else
  {
    printf '\n# S3 Backup Controls\n\n'
    printf 'SKIPPED: S3_BUCKET is not set.\n'
  } >>"$REPORT"
fi

if [[ -n "${BACKUP_VAULT_NAME:-}${BACKUP_PLAN_ID:-}${BACKUP_RESOURCE_ARN:-}" ]]; then
  run_check "AWS Backup Controls" "$SCRIPT_DIR/check_aws_backup_controls.sh"
else
  {
    printf '\n# AWS Backup Controls\n\n'
    printf 'SKIPPED: BACKUP_VAULT_NAME, BACKUP_PLAN_ID, and BACKUP_RESOURCE_ARN are not set.\n'
  } >>"$REPORT"
fi

printf 'Evidence report written to %s\n' "$REPORT"
exit "$overall_status"
