package com.anastasia.Anastasia_BackEnd.core.notification.domain;

public enum NotificationType {
    ACCOUNT_ACTIVATION,
    PASSWORD_RESET,
    WELCOME,
    EVENT_REMINDER,
    MEMBER_BIRTHDAY,
    MEMBER_REGISTRATION_SUBMITTED,
    CHILD_REGISTRATION_SUBMITTED,
    BAPTISM_REQUEST_SUBMITTED,
    MARRIAGE_CASE_SUBMITTED,
    MARRIAGE_CASE_BOTH_SUBMITTED,
    PAYMENT_RECEIVED,
    PHONE_VERIFICATION,
    NOTIFICATION
}
