package com.anastasia.Anastasia_BackEnd.modules.services.marriage.model;

public enum MarriageCaseAuditEventType {
    CASE_CREATED,
    COUNTERPART_PLACEHOLDER_CREATED,
    COUNTERPART_PAIRED,
    PARTY_SUBMITTED,
    BOTH_PARTIES_SUBMITTED,
    REQUIREMENT_SATISFIED,
    DOCUMENT_VERIFIED,
    SECRETARY_CIVIL_CHECKS_APPROVED,
    CONFESSOR_APPROVED,
    CONFESSOR_BLOCKED,
    DIOCESE_OVERRIDE_RECORDED,
    ADMIN_APPROVED,
    MANUAL_PAYMENT_RECORDED,
    PRIEST_ASSIGNED,
    SCHEDULE_CREATED,
    CEREMONY_COMPLETED,
    CERTIFICATE_PREPARED,
    CERTIFICATE_ISSUED,
    CASE_CLOSED,
    NOTE_ADDED,
    IMPEDIMENT_OPENED,
    IMPEDIMENT_RESOLVED
}
