-- event attendance tracking
CREATE TABLE IF NOT EXISTS event_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    check_in_time TIMESTAMP,
    check_in_method VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    checked_in_by UUID,
    PRIMARY KEY (id),
    CONSTRAINT fk_event_attendance_event FOREIGN KEY (event_id) REFERENCES events(event_id),
    CONSTRAINT fk_event_attendance_user FOREIGN KEY (user_id) REFERENCES users(uuid),
    CONSTRAINT fk_event_attendance_checked_in_by FOREIGN KEY (checked_in_by) REFERENCES users(uuid)
);

CREATE INDEX idx_event_attendance_event ON event_attendance(event_id);
CREATE INDEX idx_event_attendance_user ON event_attendance(user_id);
CREATE INDEX idx_event_attendance_event_status ON event_attendance(event_id, status);
